server {
    bind_address = "0.0.0.0"
    bind_port = "8081"
    trust_domain = "kest.internal"
    data_dir = "/opt/spire/data"
    log_level = "DEBUG"
    ca_subject {
        country = ["US"]
        organization = ["Kest"]
        common_name = "kest.internal"
    }
}

plugins {
    DataStore "sql" {
        plugin_data {
            database_type = "sqlite3"
            connection_string = "/opt/spire/datastore.sqlite3"
        }
    }

    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "disk" {
        plugin_data {
            keys_path = "/opt/spire/keys.json"
        }
    }
}
