"""
Template & Hydrate engine for data-safe report composition.

The Template & Hydrate pattern allows LLMs to produce report *structure* using
opaque handle XML tags — they never see the underlying sensitive data.

Placeholder format::

    <kest-handle id="hdl_a1b2c3..." safe_view="Q3 total expenditure figure"/>

The tag embeds both the opaque ``id`` (used by the gateway for ACL-checked
resolution) and the human-readable ``safe_view`` (used by the LLM to reason
about the handle's content without accessing it).

Workflow:

1. Upstream service seals sensitive data → receives an :class:`OpaqueHandle`.
2. Service embeds ``handle.to_tag()`` in the LLM prompt (safe_view only).
3. LLM produces a report skeleton that re-uses the embedded tag(s).
4. Trusted gateway calls ``TemplateEngine.hydrate()`` to:
   a. Parse all ``<kest-handle .../>`` tags from the skeleton.
   b. ACL-check and unseal every handle (all errors collected, no short-circuit).
   c. Serialise each payload with a configurable ``serializer``.
   d. Run post-hydration ``OutputValidator`` guardrails (DLP, regex, etc.).
   e. Return the fully hydrated string.

Example::

    import json
    from kest.core.vault import HandleVault, TemplateEngine
    from kest.core.framework.validators import RegexDenyListValidator

    vault = HandleVault()
    engine = TemplateEngine(vault=vault, serializer=json.dumps)

    handle = vault.seal(
        data={"total": "$1,234,567"},
        owner_principal="spiffe://example.com/data-service",
        safe_view="Q3 total expenditure figure",
        granted_principals=["spiffe://example.com/report-service"],
    )

    # Embed handle.to_tag() in the LLM prompt:
    # "Summarise the quarter. The total expenditure is stored in
    #  <kest-handle id="hdl_..." safe_view="Q3 total expenditure figure"/>"

    skeleton = f"Expenditure: {handle.to_tag()}."
    report = engine.hydrate(
        template=skeleton,
        requesting_principal="spiffe://example.com/report-service",
        output_validators=[RegexDenyListValidator([r"\\bSSN\\b"])],
    )
"""

from __future__ import annotations

import re
from typing import Any, Callable, Iterable

from kest.core.vault.errors import (
    HandleAccessDeniedError,
    HandleExpiredError,
    HandleNotFoundError,
)

# ---------------------------------------------------------------------------
# XML tag patterns
# ---------------------------------------------------------------------------

# Matches the entire self-closing <kest-handle .../> tag.
# Attributes may appear in any order; safe_view may contain spaces and
# XML entity references but not raw double-quotes (which are escaped by to_tag).
_HANDLE_TAG_RE = re.compile(r"<kest-handle\b[^>]*/\s*>")

# Extract the id attribute value from within a matched tag.
_ID_ATTR_RE = re.compile(r'\bid="(hdl_[0-9a-f]+)"')


# ---------------------------------------------------------------------------
# HydrationError
# ---------------------------------------------------------------------------


class HydrationError(Exception):
    """Raised when one or more handle resolutions fail during hydration.

    All failing handles are attempted before this exception is raised so
    the caller receives a complete picture of every ACL denial, missing
    handle, or expiry in a single pass.

    Attributes:
        errors: Mapping from ``handle_id`` to the underlying exception
            (``HandleNotFoundError``, ``HandleExpiredError``, or
            ``HandleAccessDeniedError``).
    """

    def __init__(self, errors: dict[str, Exception]) -> None:
        self.errors: dict[str, Exception] = errors
        summary = "; ".join(
            f"{hid}: {type(exc).__name__}" for hid, exc in errors.items()
        )
        super().__init__(f"Hydration failed for {len(errors)} handle(s): {summary}")


# ---------------------------------------------------------------------------
# TemplateParser
# ---------------------------------------------------------------------------


class TemplateParser:
    """Pure parsing and rendering logic for XML kest-handle templates.

    All methods are class-level; the class is stateless and never needs to
    be instantiated.  Kept separate from :class:`TemplateEngine` (SRP) so
    the regex / substitution logic can be tested in isolation.

    Placeholder format::

        <kest-handle id="hdl_..." safe_view="human readable description"/>

    The ``id`` attribute is required and must start with ``hdl_`` followed by
    hex digits.  The ``safe_view`` attribute is required for the tag to be
    well-formed (generated by :meth:`OpaqueHandle.to_tag`) but is not used
    during substitution — only the ``id`` drives handle resolution.
    Attributes may appear in any order.
    """

    #: Compiled regex matching a complete ``<kest-handle .../>`` tag.
    HANDLE_TAG_PATTERN: re.Pattern[str] = _HANDLE_TAG_RE

    #: Compiled regex extracting the ``id`` attribute from within a matched tag.
    ID_ATTR_PATTERN: re.Pattern[str] = _ID_ATTR_RE

    @classmethod
    def parse(cls, template: str) -> list[str]:
        """Return an ordered list of handle IDs found in *template*.

        Duplicates are preserved (the same handle may appear multiple times).
        Only tags with a valid ``hdl_<hex>`` id attribute are included; tags
        missing the ``id`` attribute or with a non-handle id are ignored.

        Args:
            template: The LLM-produced skeleton string to scan.

        Returns:
            Ordered list of handle ID strings.  ``[]`` if none found.
        """
        ids: list[str] = []
        for tag_match in cls.HANDLE_TAG_PATTERN.finditer(template):
            id_match = cls.ID_ATTR_PATTERN.search(tag_match.group(0))
            if id_match:
                ids.append(id_match.group(1))
        return ids

    @classmethod
    def render(cls, template: str, substitutions: dict[str, str]) -> str:
        """Replace every ``<kest-handle id="X" .../>`` tag in *template*.

        Tags whose ``id`` is in *substitutions* are replaced with the
        corresponding value.  Tags absent from *substitutions* are left
        untouched (safety valve — :class:`TemplateEngine` raises
        :class:`HydrationError` before reaching this step for any
        unresolvable handles).

        Args:
            template: The raw skeleton string.
            substitutions: Mapping from handle ID to its serialised value.

        Returns:
            The hydrated string.
        """

        def _replace(tag_match: re.Match[str]) -> str:
            tag = tag_match.group(0)
            id_match = cls.ID_ATTR_PATTERN.search(tag)
            if id_match:
                handle_id = id_match.group(1)
                return substitutions.get(handle_id, tag)
            return tag

        return cls.HANDLE_TAG_PATTERN.sub(_replace, template)


# ---------------------------------------------------------------------------
# TemplateEngine
# ---------------------------------------------------------------------------


class TemplateEngine:
    """Orchestrates parse → ACL-checked unseal → substitution → validation.

    Args:
        vault: The :class:`~kest.core.vault.HandleVault` instance to unseal
            handles from.
        serializer: Callable that converts unsealed data to a string for
            substitution into the template.  Defaults to :func:`str`.
            Pass ``json.dumps`` for JSON formatting, ``yaml.dump`` for YAML, etc.

    Example::

        import json
        engine = TemplateEngine(vault=vault, serializer=json.dumps)
    """

    def __init__(
        self,
        vault: Any,  # HandleVault — typed as Any to avoid circular import
        serializer: Callable[[Any], str] = str,
    ) -> None:
        self._vault = vault
        self._serializer = serializer

    def hydrate(
        self,
        template: str,
        requesting_principal: str,
        output_validators: Iterable[Any] = (),
    ) -> str:
        """Hydrate *template* by resolving all ``<kest-handle .../>`` tags.

        Steps:

        1. Parse all handle IDs from *template* (unique IDs for unseal;
           duplicate tags are substituted at all positions).
        2. Attempt ``vault.unseal()`` for every unique handle ID.  **All**
           errors are collected — no short-circuit on first failure.
        3. If any errors occurred, raise :class:`HydrationError`.
        4. Substitute every ``<kest-handle .../>`` tag with
           ``serializer(data)``.
        5. Run *output_validators* on the final string.
        6. Return the hydrated string.

        Args:
            template: LLM-produced skeleton string with ``<kest-handle .../>``
                placeholders.
            requesting_principal: The SPIFFE URI (or other principal string)
                of the component performing the hydration.  ACL-checked against
                each handle's ``granted_principals`` / ``owner_principal``.
            output_validators: Optional sequence of :class:`OutputValidator`
                instances run after hydration (e.g. DLP / regex guardrails).

        Returns:
            The fully hydrated report string.

        Raises:
            HydrationError: One or more handles failed ACL / not-found /
                expiry checks.  ``HydrationError.errors`` maps each failing
                handle ID to its underlying exception.
            OutputValidationError: The hydrated string failed a post-hydration
                validator.
        """
        all_ids = TemplateParser.parse(template)
        unique_ids = list(dict.fromkeys(all_ids))  # deduplicate, preserve order

        # --- Step 2: attempt all unseals, collect errors ---
        resolved: dict[str, Any] = {}
        errors: dict[str, Exception] = {}

        for handle_id in unique_ids:
            try:
                resolved[handle_id] = self._vault.unseal(
                    handle_id, requesting_principal
                )
            except (
                HandleNotFoundError,
                HandleExpiredError,
                HandleAccessDeniedError,
            ) as exc:
                errors[handle_id] = exc

        # --- Step 3: raise collected errors ---
        if errors:
            raise HydrationError(errors)

        # --- Step 4: build substitutions and render ---
        substitutions = {hid: self._serializer(data) for hid, data in resolved.items()}
        result = TemplateParser.render(template, substitutions)

        # --- Step 5: run output validators ---
        for validator in output_validators:
            validator.validate(result)

        return result
